# Generated by Django 3.0.8 on 2020-09-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200914_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='text_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.CharField(max_length=40)),
                ('theading', models.CharField(max_length=128)),
                ('tfor_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfor_class', to='school.classroom')),
            ],
        ),
    ]
