# Generated by Django 3.0.8 on 2020-09-14 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200914_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='text_post',
        ),
    ]
