# Generated by Django 3.0.8 on 2020-09-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200914_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='urgency',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
