# Generated by Django 3.0.8 on 2020-09-26 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_announcement_urgency'),
    ]

    operations = [
        migrations.CreateModel(
            name='poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('choice1', models.CharField(max_length=40)),
                ('choice2', models.CharField(max_length=40)),
                ('choice3', models.CharField(blank='True', max_length=40)),
                ('choice4', models.CharField(blank='True', max_length=40)),
                ('choice5', models.CharField(blank='True', max_length=40)),
                ('choice6', models.CharField(blank='True', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='pollvalues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.ManyToManyField(blank='True', related_name='vote1', to=settings.AUTH_USER_MODEL)),
                ('choice2', models.ManyToManyField(blank='True', related_name='vote2', to=settings.AUTH_USER_MODEL)),
                ('choice3', models.ManyToManyField(blank='True', related_name='vote3', to=settings.AUTH_USER_MODEL)),
                ('choice4', models.ManyToManyField(blank='True', related_name='vote4', to=settings.AUTH_USER_MODEL)),
                ('choice5', models.ManyToManyField(blank='True', related_name='vote5', to=settings.AUTH_USER_MODEL)),
                ('choice6', models.ManyToManyField(blank='True', related_name='vote6', to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_parent', to='school.poll')),
            ],
        ),
    ]
