# Generated by Django 3.0.8 on 2020-09-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20200926_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_add', to='school.poll'),
            preserve_default=False,
        ),
    ]
