# Generated by Django 3.0.8 on 2020-09-26 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_announcement_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='poll',
        ),
        migrations.AddField(
            model_name='poll',
            name='announcement_parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_player', to='school.announcement'),
            preserve_default=False,
        ),
    ]
