# Generated by Django 3.0.8 on 2020-09-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200926_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='poll',
        ),
    ]
