# Generated by Django 3.0.8 on 2020-09-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_delete_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coverphoto',
            field=models.CharField(default='https://innsida.ntnu.no/documents/10157/2548972475/user-profile-empty.png', max_length=1024),
        ),
    ]
