# Generated by Django 3.0.8 on 2020-09-29 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_user_coverphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='students_child',
            field=models.ManyToManyField(blank='True', related_name='student_child', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='coverphoto',
            field=models.CharField(blank='True', max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepicture',
            field=models.CharField(blank='True', default='https://innsida.ntnu.no/documents/10157/2548972475/user-profile-empty.png', max_length=1024),
        ),
    ]
