# Generated by Django 3.0.8 on 2020-10-01 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20200930_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='postobject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=256)),
                ('attached_image', models.CharField(blank='True', max_length=1024)),
                ('uploadedfile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='coverphoto',
            field=models.FileField(blank='True', default='defaultcoverphoto.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepicture',
            field=models.FileField(blank='True', default='defaultprofile.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.AddField(
            model_name='postobject',
            name='parent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_ann',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_ann', to='school.postobject'),
        ),
    ]
