# Generated by Django 3.0.8 on 2020-10-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20201001_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postobject',
            name='attached_image',
        ),
        migrations.AddField(
            model_name='classroom',
            name='RSA',
            field=models.CharField(default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classcoverphoto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
