# Generated by Django 3.0.8 on 2020-10-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20201003_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.CharField(blank='True', max_length=256),
        ),
    ]
