# Generated by Django 3.0.8 on 2020-10-03 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_classroom_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('attachedlink', models.CharField(max_length=256)),
                ('attachedfile', models.FileField(blank=True, null=True, upload_to='')),
                ('day', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('completed_students', models.ManyToManyField(blank='True', related_name='completed_students', to=settings.AUTH_USER_MODEL)),
                ('for_class', models.ManyToManyField(blank='True', related_name='for_classroom', to='school.classroom')),
            ],
        ),
    ]
