# Generated by Django 3.0.8 on 2020-10-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='for_class',
        ),
        migrations.AddField(
            model_name='activity',
            name='for_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='for_classroom', to='school.classroom'),
            preserve_default=False,
        ),
    ]
