# Generated by Django 3.0.8 on 2020-10-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20201003_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='attachedlink',
            field=models.CharField(blank='True', max_length=256),
        ),
    ]
