# Generated by Django 3.0.8 on 2020-10-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20201005_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='day',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='month',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='year',
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
