# Generated by Django 3.0.8 on 2020-10-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_auto_20201006_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='status',
            new_name='open',
        ),
    ]
