# Generated by Django 3.0.8 on 2020-10-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20201006_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='open',
            new_name='closed',
        ),
    ]
