# Generated by Django 3.0.8 on 2020-10-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_auto_20201006_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='percent',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
