# Generated by Django 3.0.8 on 2020-10-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_activity_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
